on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: KEINOS/Practice_GitHub_Action@v0.0.3
      with:
        who-to-greet: 'Mona the Octocat'
      env:
        MY_SECRET_VALUE: ${{ secrets.SuperSecret }}
        MY_SECRET_VALUEX: ${{ secrets.MY_SECRET_VALUE }}
    # Use the output from the `hello` step
    - name: Get the output time
      env:
        MY_SECRET_VALUE: ${{ secrets.SuperSecret }}
        MY_SECRET_VALUEY: ${{ secrets.MY_SECRET_VALUE }}
      run: echo "Halloo! The time was ${{ steps.hello.outputs.time }}" && echo "ENV info are:" && env
