on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: KEINOS/Practice_GitHub_Action@v0.0.14
      with:
        # Workflow の引数として渡す値
        who-to-greet: 'Mona the Octocat (From who-to-gree @ client workflow/main.yml)'
      env:
        # リポジトリの GitHub 設定にある "Secrets" にて設定された環境変数を渡す
        MY_SECRET_VALUE: ${{ secrets.MY_SECRET_VALUE }}
    # Use the output from the ID `hello` step
    - name: Get the output time
      env:
        MY_SECRET_VALUE: ${{ secrets.MY_SECRET_VALUE }}
      run: echo "Halloo! The time was ${{ steps.hello.outputs.time }}" && echo "ENV info in output time step are:" && env
