on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Check outside Docker (Preparation)
      run: |
        sudo apt-get --quiet update --yes
        sudo apt install tree
        echo 'main.yml:'
        ls -la && pwd
        tree -d /
    - name: Hello world action step
      id: hello
      uses: KEINOS/Practice_GitHub_Action@v0.0.7
      with:
        # Workflow の引数として渡す値
        who-to-greet: 'Mona the Octocat (From who-to-gree @ client workflow/main.yml)'
      env:
        MY_SECRET_VALUE: ${{ secrets.MY_SECRET_VALUE }}
    # Use the output from the ID `hello` step
    - name: Get the output time
      env:
        MY_SECRET_VALUE: ${{ secrets.MY_SECRET_VALUE }}
      run: echo "Halloo! The time was ${{ steps.hello.outputs.time }}" && echo "ENV info in output time step are:" && env
